name: Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Build dependencies
        run: helm dependency build charts/playwright-manager

      - name: Lint Helm chart
        run: helm lint charts/playwright-manager

  release:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Build dependencies
        run: helm dependency build charts/playwright-manager

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  push-to-ghcr:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and push Helm chart to GHCR
        run: |
          cd charts/playwright-manager
          helm dependency build
          CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
          helm package .
          helm push playwright-manager-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
